import Head from 'next/head'
import styles from '../styles/Home.module.css'
import dynamic from 'next/dynamic'
import { Text, Container } from '@nextui-org/react'

const TheTable = dynamic(
    () => import('../components/Links'),
    { ssr: false, loading: () => <p>Loading...</p> }
  )

  const Nav = dynamic(
    () => import('../components/Nav'),
    { ssr: false, loading: () => <p>Loading...</p> }
  )

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>URL Shortener</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav />
      <Container>
        <Text h1 className={styles.title}>
          Shorten URLs
        </Text>
        <TheTable />
      </Container>
    </div>
  )
}